import "./globals.css";
import Header from "./components/Header/Header";

export const metadata = {
  title: "Rocio Alonso",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Header></Header>
        {children}
      </body>
    </html>
  );
}
